jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            (exit 1) || echo "ok done"

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step"
    when: always

  artifacts:
    docker:
      - image: python:3.6
    steps:
      - run: echo "hello" > hello.txt
      - store_artifacts:
          path: hello.txt
          destination: /tmp

filters: &only-main
  branches:
    only: main
    
workflows:
  version: 2
  django:
    jobs:
      - build:
          filters: *only-main
      - test:
          requires:
            - build
          filters: *only-main
      - integration:
          requires:
            - test
          filters: *only-main
      - prod:
          requires:
            - integration
          filters: *only-main
      - artifacts:
          requires:
            - prod
          filters: *only-main
